#!/bin/bash

AR_ENV_PATH=.
NAME=SGAREnvironment
VERSION=0.3.5
AR_ENV_DIR=$AR_ENV_PATH/$NAME-v$VERSION

RESOURCE_PATH=Resources
IMAGE_PATH=$RESOURCE_PATH/Images
AR_ENV_IMAGE_DIR=$AR_ENV_DIR/Images

HEADER_DIR=$AR_ENV_DIR/Headers

LIBRARY_NAME=lib$NAME.a
SIM_LIBRARY_NAME=lib$NAME-sim.a

LIBRARY_PATH=build/Release-iphoneos/$LIBRARY_NAME
SIM_LIBRARY_PATH=build/Release-iphonesimulator/$LIBRARY_NAME

ROOT_HEADER_PATH=./Classes

HEADER_DOC_DIR=Resources/HeaderDoc
DOC_DIR=$AR_ENV_DIR/Documentation
CSS_DIR=$DOC_DIR/css

rm -rf $AR_ENV_DIR
mkdir $AR_ENV_DIR $AR_ENV_DIR/iphoneos $AR_ENV_DIR/iphonesimulator $DOC_DIR $HEADER_DIR $CSS_DIR

HEADER_FILES=$(find $ROOT_HEADER_PATH -name "*.h")
for header_file in $HEADER_FILES
do
  echo Copying $header_file
  cp $header_file $HEADER_DIR/
done

SDKs=( iphoneos3.1 iphonesimulator3.1 )

for sdk in ${SDKs[@]}
do
  xcodebuild -target $NAME -sdk $sdk clean build
  if [ $? -gt 0 ]; then
      echo "ERROR!"
      exit
  fi

done

# Static Libraries
cp $LIBRARY_PATH $AR_ENV_DIR/iphoneos/$LIBRARY_NAME
cp $SIM_LIBRARY_PATH $AR_ENV_DIR/iphonesimulator/$LIBRARY_NAME

# Produce HeaderDocs
cp -r $HEADER_DOC_DIR/Images $DOC_DIR
cp $HEADER_DOC_DIR/Documentation.config headerDoc2HTML.config
cp $HEADER_DOC_DIR/SDK.hdoc $AR_ENV_DIR/this.hdoc
cp $HEADER_DOC_DIR/TOCmaster.css $CSS_DIR

headerdoc2HTML -H -o $DOC_DIR $HEADER_DIR
gatherheaderdoc $DOC_DIR $NAME.html

rm headerDoc2HTML.config
rm $AR_ENV_DIR/this.hdoc

cp README $AR_ENV_DIR
cp LICENSE.txt $AR_ENV_DIR

# Copy images
mkdir $AR_ENV_IMAGE_DIR
cp -r $IMAGE_PATH/SG*.png $AR_ENV_IMAGE_DIR

for i in $*
do
	case $i in
	--zip)
		zip -r $AR_ENV_DIR.zip $AR_ENV_DIR
	esac
done
